name: user_support_mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animations: ^2.0.1
  cupertino_icons: ^1.0.2
  file_picker: ^4.0.0
  flutter:
    sdk: flutter
  flutter_slidable: ^0.6.0
  flutter_svg: ^0.22.0
  google_fonts: ^4.0.1
  http: ^0.13.3
  shimmer: ^2.0.0
  d2_touch:
    path: ../d2-touch
  dio: ^5.1.1
  freezed_annotation: ^0.15.0
  intl: ^0.17.0
  provider: ^6.0.3
  reflectable: ^4.0.5
  flutter_easyloading: ^3.0.5
  # package_info_plus: ^1.4.2
  lottie: ^2.5.0
  internet_connection_checker_plus: ^1.0.1
  get: ^4.6.5
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  lint: ^1.5.3
  # freezed: ^0.15.1+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
